$("#notice2").show().slideDown();
  setTimeout(function(){
      $("#notice2").show();        
  },105000);
$("#rev-ad,#shade").show().slideDown();
  setTimeout(function(){
      $("#rev-ad,#shade").show();        
  },60000);
$("#notice").show().slideDown();
  setTimeout(function(){
      $("#notice").show();        
  },150000);
$(document).ready(function(){
    $("#hide2").click(function(){
        $("#rev-ad,#shade").hide();
    });
});
$(document).ready(function(){
    $("#hide3").click(function(){
        $("#notice2").hide();
    });
});
$(document).ready(function(){
    $("#hide").click(function(){
        $("#notice").hide();
    });
});
