$("#rev-ad,#shade").show().slideDown();
  setTimeout(function(){
      $("#rev-ad,#shade").show();        
  },65000);
$(document).ready(function(){
    $("#hide2").click(function(){
        $("#rev-ad,#shade").hide();
    });
});
