$("#rev-ad,#shade").show().slideDown();
  setTimeout(function(){
      $("#rev-ad,#shade").show();        
  },50000);
$(document).ready(function(){
    $(".xfs").click(function(){
        $("#fs").hide();
    });
});
